var data = require('./inputs.json')
Feature('Kalanjiam');

Scenario('login with valid username and password', (I) => {
    I.amOnPage(data['URL'])
    I.click(data['xpath']['login_button'])
    I.fillField(data['xpath']['email_add'],data['credentials']['username'])
    I.fillField(data['xpath']['password_x'],data['credentials']['password'])
    I.click(data['xpath']['login_into'])
    I.wait(5)
    I.click(data['xpath']['logout'])
    I.wait(2)
});
Scenario('Try to create new account with existing details', (I) => {
    I.amOnPage(data['URL'])
    I.click(data['xpath']['signup'])
    I.wait(2)
    I.fillField(data['xpath']['firstname'],data['credentials']['firstname'])
    I.wait(2)
    I.fillField(data['xpath']['lastname'],data['credentials']['lastname'])
    I.wait(2)
    I.fillField(data['xpath']['Email'],data['credentials']['email_id'])
    I.wait(2)
    I.fillField(data['xpath']['phone_number'],data['credentials']['phone_no'])
    I.wait(2)
    I.fillField(data['xpath']['newpassword'],data['credentials']['new_password'])
    I.fillField(data['xpath']['repeat_pwd'],data['credentials']['new_password'])
    I.wait(2)
    I.click(data['xpath']['create_button'])
    I.wait(5)
    I.see('Email Id already Exist')
    I.say('scenario pass')

});
Scenario('check whether all fields in signup page should be mandatory or not?', (I) => {
    I.amOnPage(data['URL'])
    I.click(data['xpath']['signup'])
    I.wait(2)
    I.fillField(data['xpath']['lastname'],data['credentials']['lastname'])
    I.fillField(data['xpath']['Email'],data['credentials']['email_id'])
    I.fillField(data['xpath']['phone_number'],data['credentials']['phone_no'])
    I.fillField(data['xpath']['newpassword'],data['credentials']['new_password'])
    I.fillField(data['xpath']['repeat_pwd'],data['credentials']['new_password'])
    I.wait(2)
    I.click(data['xpath']['create_button'])
    I.wait(2)
    I.seeElement(data['error']['mandatory_firstname'])
    I.say('First name-manadatory check-scenario pass')
    I.wait(2)
    I.fillField(data['xpath']['firstname'],data['credentials']['firstname'])
    I.wait(2)
    I.clearField(data['xpath']['lastname'],data['credentials']['lastname'])
    I.wait(2)
    I.click(data['xpath']['create_button'])
    I.seeElement(data['error']['mandatory_secondname'])
    I.say('lastname-manadatory check-scenario pass')
    I.wait(2)
    I.clearField(data['xpath']['Email'],data['credentials']['email_id'])
    I.fillField(data['xpath']['lastname'],data['credentials']['lastname'])
    I.wait(2)
    I.click(data['xpath']['create_button'])
    I.seeElement(data['error']['mandatory_email'])
    I.say('emailid-manadatory check-scenario pass')
    I.wait(2)
    I.clearField(data['xpath']['phone_number'],data['credentials']['phone_no'])
    I.fillField(data['xpath']['Email'],data['credentials']['email_id'])
    I.wait(2)
    I.click(data['xpath']['create_button'])
    I.seeElement(data['error']['mandatory_phone'])
    I.say('phoneno-manadatory check-scenario pass')
    I.wait(2)
});
Scenario('check whether all fields in signup page should be mandatory or not?', (I) => {
        I.amOnPage(data['URL'])
});