var inputs = require('./inputs.json')
Feature('Kalanjiam');

Scenario('login with valid username and password', (I) => {
    I.amOnPage(inputs['URL'])
    I.click(inputs['xpath']['login_button'])
    I.fillField(inputs['xpath']['email_add'],inputs['credentials']['username'])
    I.fillField(inputs['xpath']['password_x'],inputs['credentials']['password'])
    I.click(inputs['xpath']['login_into'])
    I.wait(5)
    I.click(inputs['xpath']['logout'])
    I.wait(2)
});
Scenario('Try to create new account with existing details', (I) => {
    I.amOnPage(inputs['URL'])
    I.click(inputs['xpath']['signup'])
    I.wait(2)
    I.fillField(inputs['xpath']['firstname'],inputs['credentials']['firstname'])
    I.wait(2)
    I.fillField(inputs['xpath']['lastname'],inputs['credentials']['lastname'])
    I.wait(2)
    I.fillField(inputs['xpath']['Email'],inputs['credentials']['email_id'])
    I.wait(2)
    I.fillField(inputs['xpath']['phone_number'],inputs['credentials']['phone_no'])
    I.wait(2)
    I.fillField(inputs['xpath']['newpassword'],inputs['credentials']['new_password'])
    I.fillField(inputs['xpath']['repeat_pwd'],inputs['credentials']['new_password'])
    I.wait(2)
    I.click(inputs['xpath']['create_button'])
    I.wait(5)
    I.see('Email Id already Exist')
    I.say('scenario pass')

});
Scenario('check whether all fields in signup page should be mandatory or not?', (I) => {
    I.amOnPage(inputs['URL'])
    I.click(inputs['xpath']['signup'])
    I.wait(2)
    I.fillField(inputs['xpath']['lastname'],inputs['credentials']['lastname'])
    I.fillField(inputs['xpath']['Email'],inputs['credentials']['email_id'])
    I.fillField(inputs['xpath']['phone_number'],inputs['credentials']['phone_no'])
    I.fillField(inputs['xpath']['newpassword'],inputs['credentials']['new_password'])
    I.fillField(inputs['xpath']['repeat_pwd'],inputs['credentials']['new_password'])
    I.wait(2)
    I.click(inputs['xpath']['create_button'])
    I.wait(2)
    I.seeElement(inputs['error']['mandatory_firstname'])
    I.say('First name-manadatory check-scenario pass')
    I.wait(2)
    I.fillField(inputs['xpath']['firstname'],inputs['credentials']['firstname'])
    I.wait(2)
    I.clearField(inputs['xpath']['lastname'],inputs['credentials']['lastname'])
    I.wait(2)
    I.click(inputs['xpath']['create_button'])
    I.seeElement(inputs['error']['mandatory_secondname'])
    I.say('lastname-manadatory check-scenario pass')
    I.wait(2)
    I.clearField(inputs['xpath']['Email'],inputs['credentials']['email_id'])
    I.fillField(inputs['xpath']['lastname'],inputs['credentials']['lastname'])
    I.wait(2)
    I.click(inputs['xpath']['create_button'])
    I.seeElement(inputs['error']['mandatory_email'])
    I.say('emailid-manadatory check-scenario pass')
    I.wait(2)
    I.clearField(inputs['xpath']['phone_number'],inputs['credentials']['phone_no'])
    I.fillField(inputs['xpath']['Email'],inputs['credentials']['email_id'])
    I.wait(2)
    I.click(inputs['xpath']['create_button'])
    I.seeElement(inputs['error']['mandatory_phone'])
    I.say('phoneno-manadatory check-scenario pass')
    I.wait(2)
});
Scenario('check whether all fields in signup page should be mandatory or not?', (I) => {
        I.amOnPage(inputs['URL'])
});